// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemoryNegativeFeedbackReason } from "./MemoryNegativeFeedbackReason";

export type MemoryNegativeFeedbackRecord = { threadId: string, sourceUpdatedAt: number, rolloutSlug?: string | null, reason: MemoryNegativeFeedbackReason, createdAt: number, updatedAt: number, };
