// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MemoryHealthArtifact = { kind: string, path: string, exists: boolean, isFile: boolean, readable: boolean, sizeBytes: number | null, };
