// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemoryHealthSeverity } from "./MemoryHealthSeverity";

export type MemoryHealthIssue = { severity: MemoryHealthSeverity, code: string, message: string, };
