// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemoryDirectoryHealth } from "./MemoryDirectoryHealth";
import type { MemoryHealthRolloutSummary } from "./MemoryHealthRolloutSummary";

export type MemoryHealthRolloutSummarySet = { directory: MemoryDirectoryHealth, expected: Array<MemoryHealthRolloutSummary>, stale: Array<MemoryHealthRolloutSummary>, };
